### ISSUE TITLE
tensorflow.python.framework.errors_impl.DataLossError: <exception str() failed>

### ISSUE THREAD

**Issue by ZhangYK124** [MVIG-SJTU/WSHP#13]
zyk@zyk:~/下载/WSHP-master/parsing_network$ python inference.py /home/zyk/下载/WSHP-master/parsing_network/img/ /home/zyk/下载/WSHP-master/parsing_network/models/final_model/model.ckpt-19315.data-00000-of-00001
WARNING:tensorflow:From inference.py:85: calling expand_dims (from tensorflow.python.ops.array_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
WARNING:tensorflow:From inference.py:96: calling argmax (from tensorflow.python.ops.math_ops) with dimension is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
2018-09-05 13:23:32.405096: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /home/zyk/下载/WSHP-master/parsing_network/models/final_model/model.ckpt-19315.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2018-09-05 13:23:32.405500: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /home/zyk/下载/WSHP-master/parsing_network/models/final_model/model.ckpt-19315.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2018-09-05 13:23:32.405530: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at save_restore_tensor.cc:170 : Data loss: Unable to open table file /home/zyk/下载/WSHP-master/parsing_network/models/final_model/model.ckpt-19315.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "inference.py", line 136, in <module>
    main()
  File "inference.py", line 110, in main
    load(loader, sess, args.model_weights)
  File "inference.py", line 56, in load
    saver.restore(sess, ckpt_path)
  File "/home/zyk/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1725, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/zyk/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/zyk/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/zyk/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/zyk/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: <exception str() failed>

**Comment by Adarine99** [comment]
here is my command:
 python inference.py ./dataset ./models/final_model/model.ckpt-19315 --data_list ./dataset/pascal_test.txt
 worked fine.Just for your reference.

**Comment by Fang-Haoshu** [comment]
@yuli1994 Thanks, you are right
