### ISSUE TITLE
inference.py ERROR

### ISSUE THREAD

**Issue by donghaoye** [MVIG-SJTU/WSHP#2]
No such file or directoryr traceback): dataset/my_test/20180521225238.jpg
         [[Node: create_inputs/ReadFile = ReadFile[_device="/job:localhost/replica:0/task:0/device:CPU:0"](create_inputs/input_producer/Gather)]]

I sure it is exits
donghaoye@amax1:/data1/donghaoye/workspace/WSHP/parsing_network$ ls dataset/my_test/20180521225238.jpg

**Comment by donghaoye** [comment]
Where is the 'dance.txt'?
How can I format my data_list.txt

**Comment by Fang-Haoshu** [comment]
It works on my side. Try using the absolute path to the image dir and list img name in the txt file

**Comment by donghaoye** [comment]
I fixed it.
the .txt should format 
xxxx.png xxxx.png
aaaa.png aaaa.png

**Comment by Fang-Haoshu** [comment]
Oh, great! But it should work with 
xxxx.png
aaaa.png

See here: https://github.com/MVIG-SJTU/WSHP/blob/master/parsing_network/deeplab_resnet/image_reader.py#L88

**Comment by donghaoye** [comment]
I just to generate test.jpg label.

**Comment by Fang-Haoshu** [comment]
I mean the .txt can also format
xxxx.png
aaaa.png

**Comment by donghaoye** [comment]
get it

**Comment by ZhangYK124** [comment]
你们好，我想请教一个问题如下：

我的路径目录如下：
dataset
    dance.txt
deeplab_resnet
kaffe
misc
models
output
VIPeR
    cam_a/000_45.bmp
inference.py

我的dance.txt里面是图片的路径：/home/zyk/桌面/WSHP-master/parsing_network/VIPeR/cam_a/000_45.bmp

我在运行inference.py的时候，终端输入的是：
python inference.py /home/zyk/桌面/WSHP-master/parsing_network/VIPeR/cam_a /home/zyk/桌面/WSHP-master/parsing_network/models

但是运行程序的时候总是报错如下：

### 2018-07-03 21:13:56.618526: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /home/zyk/桌面/WSHP-master/parsing_network/models: Failed precondition: /home/zyk/桌面/WSHP-master/parsing_network/models; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
2018-07-03 21:13:56.620048: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /home/zyk/桌面/WSHP-master/parsing_network/models: Failed precondition: /home/zyk/桌面/WSHP-master/parsing_network/models; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
2018-07-03 21:13:56.620080: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at save_restore_tensor.cc:170 : Data loss: Unable to open table file /home/zyk/桌面/WSHP-master/parsing_network/models: Failed precondition: /home/zyk/桌面/WSHP-master/parsing_network/models; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "inference.py", line 136, in <module>
    main()
  File "inference.py", line 110, in main
    load(loader, sess, args.model_weights)
  File "inference.py", line 56, in load
    saver.restore(sess, ckpt_path)
  File "/home/zyk/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1802, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/zyk/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/zyk/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/zyk/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/zyk/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: <exception str() failed>


请问我是什么地方有问题呢？非常期待您的回答，谢谢
