### ISSUE TITLE
inference.py运行报错

### ISSUE THREAD

**Issue by ZhangYK124** [MVIG-SJTU/WSHP#6]
你们好，我想请教一个问题如下：

我的路径目录如下：
dataset
dance.txt
deeplab_resnet
kaffe
misc
models
output
VIPeR
cam_a/000_45.bmp
inference.py

我的dance.txt里面是图片的路径：/home/zyk/桌面/WSHP-master/parsing_network/VIPeR/cam_a/000_45.bmp

我在运行inference.py的时候，终端输入的是：
python inference.py /home/zyk/桌面/WSHP-master/parsing_network/VIPeR/cam_a /home/zyk/桌面/WSHP-master/parsing_network/models

但是运行程序的时候总是报错如下：

2018-07-03 21:13:56.618526: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /home/zyk/桌面/WSHP-master/parsing_network/models: Failed precondition: /home/zyk/桌面/WSHP-master/parsing_network/models; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?

2018-07-03 21:13:56.620048: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /home/zyk/桌面/WSHP-master/parsing_network/models: Failed precondition: /home/zyk/桌面/WSHP-master/parsing_network/models; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
2018-07-03 21:13:56.620080: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at save_restore_tensor.cc:170 : Data loss: Unable to open table file /home/zyk/桌面/WSHP-master/parsing_network/models: Failed precondition: /home/zyk/桌面/WSHP-master/parsing_network/models; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
File "inference.py", line 136, in 
main()
File "inference.py", line 110, in main
load(loader, sess, args.model_weights)
File "inference.py", line 56, in load
saver.restore(sess, ckpt_path)
File "/home/zyk/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1802, in restore
{self.saver_def.filename_tensor_name: save_path})
File "/home/zyk/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
run_metadata_ptr)
File "/home/zyk/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
feed_dict_tensor, options, run_metadata)
File "/home/zyk/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
run_metadata)
File "/home/zyk/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: <exception str() failed>

请问我是什么地方有问题呢？非常期待您的回答，谢谢

**Comment by Fang-Haoshu** [comment]
路径要指向图片和模型
另外无需重复提问
